/* 
 * SQL Server 2017 Reporting Services REST API
 *
 * The SQL Server 2017 Reporting Services REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://docs.microsoft.com/sql/reporting-services/reporting-services-developer-documentation  __Team Blog:__ https://blogs.msdn.microsoft.com/sqlrsteamblog  __Support forums:__ https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlreportingservices 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.SSRS.Swagger.Api;
using IO.SSRS.Swagger.Model;
using IO.SSRS.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.SSRS.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReportParameterDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportParameterDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for ReportParameterDefinition
        //private ReportParameterDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportParameterDefinition
            //instance = new ReportParameterDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportParameterDefinition
        /// </summary>
        [Test]
        public void ReportParameterDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportParameterDefinition
            //Assert.IsInstanceOfType<ReportParameterDefinition> (instance, "variable 'instance' is a ReportParameterDefinition");
        }


        /// <summary>
        /// Test the property 'AllowBlank'
        /// </summary>
        [Test]
        public void AllowBlankTest()
        {
            // TODO unit test for the property 'AllowBlank'
        }
        /// <summary>
        /// Test the property 'DefaultValues'
        /// </summary>
        [Test]
        public void DefaultValuesTest()
        {
            // TODO unit test for the property 'DefaultValues'
        }
        /// <summary>
        /// Test the property 'DefaultValuesIsNull'
        /// </summary>
        [Test]
        public void DefaultValuesIsNullTest()
        {
            // TODO unit test for the property 'DefaultValuesIsNull'
        }
        /// <summary>
        /// Test the property 'DefaultValuesQueryBased'
        /// </summary>
        [Test]
        public void DefaultValuesQueryBasedTest()
        {
            // TODO unit test for the property 'DefaultValuesQueryBased'
        }
        /// <summary>
        /// Test the property 'Dependencies'
        /// </summary>
        [Test]
        public void DependenciesTest()
        {
            // TODO unit test for the property 'Dependencies'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'MultiValue'
        /// </summary>
        [Test]
        public void MultiValueTest()
        {
            // TODO unit test for the property 'MultiValue'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Nullable'
        /// </summary>
        [Test]
        public void NullableTest()
        {
            // TODO unit test for the property 'Nullable'
        }
        /// <summary>
        /// Test the property 'ParameterState'
        /// </summary>
        [Test]
        public void ParameterStateTest()
        {
            // TODO unit test for the property 'ParameterState'
        }
        /// <summary>
        /// Test the property 'ParameterType'
        /// </summary>
        [Test]
        public void ParameterTypeTest()
        {
            // TODO unit test for the property 'ParameterType'
        }
        /// <summary>
        /// Test the property 'ParameterVisibility'
        /// </summary>
        [Test]
        public void ParameterVisibilityTest()
        {
            // TODO unit test for the property 'ParameterVisibility'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Test]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'PromptUser'
        /// </summary>
        [Test]
        public void PromptUserTest()
        {
            // TODO unit test for the property 'PromptUser'
        }
        /// <summary>
        /// Test the property 'QueryParameter'
        /// </summary>
        [Test]
        public void QueryParameterTest()
        {
            // TODO unit test for the property 'QueryParameter'
        }
        /// <summary>
        /// Test the property 'ValidValues'
        /// </summary>
        [Test]
        public void ValidValuesTest()
        {
            // TODO unit test for the property 'ValidValues'
        }
        /// <summary>
        /// Test the property 'ValidValuesIsNull'
        /// </summary>
        [Test]
        public void ValidValuesIsNullTest()
        {
            // TODO unit test for the property 'ValidValuesIsNull'
        }
        /// <summary>
        /// Test the property 'ValidValuesQueryBased'
        /// </summary>
        [Test]
        public void ValidValuesQueryBasedTest()
        {
            // TODO unit test for the property 'ValidValuesQueryBased'
        }

    }

}
