/*
 * Power BI Report Server REST API
 * The Power BI Report Server REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Since Power BI Report Server is a superset of SQL Server Reporting Services, the Power BI Report Server REST API is a superset of the  [SQL Server Reporting Services REST API](https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0).  __Power BI Report Server API Additions__ * January 2019 Release   * /PowerBIReports({Id})/DataModelRoles (GET)   * /PowerBIReports({Id})/DataModelRoleAssignments (GET & PUT)  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://powerbi.microsoft.com/documentation/reportserver-developer-handbook-overview/  __Team Blog:__  https://powerbi.microsoft.com/blog/  __Support forums:__  https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer 
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PowerBiReportServerRestApi);
  }
}(this, function(expect, PowerBiReportServerRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PowerBiReportServerRestApi.ExtensionsApi();
  });

  describe('(package)', function() {
    describe('ExtensionsApi', function() {
      describe('getExtensionParameters', function() {
        it('should call getExtensionParameters successfully', function(done) {
          // TODO: uncomment, update parameter values for getExtensionParameters call and complete the assertions
          /*
          var id = "id_example";

          instance.getExtensionParameters(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(PowerBiReportServerRestApi.ExtensionParameter);
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.displayName).to.be.a('string');
              expect(data.displayName).to.be("");
              expect(data.required).to.be.a('boolean');
              expect(data.required).to.be(false);
              expect(data.readOnly).to.be.a('boolean');
              expect(data.readOnly).to.be(false);
              expect(data.value).to.be.a('string');
              expect(data.value).to.be("");
              expect(data.error).to.be.a('string');
              expect(data.error).to.be("");
              expect(data.encrypted).to.be.a('boolean');
              expect(data.encrypted).to.be(false);
              expect(data.isPassword).to.be.a('boolean');
              expect(data.isPassword).to.be(false);
              {
                let dataCtr = data.validValues;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(PowerBiReportServerRestApi.ValidValue);
                  expect(data.label).to.be.a('string');
                  expect(data.label).to.be("");
                  expect(data.value).to.be.a('string');
                  expect(data.value).to.be("");
                }
              }
              expect(data.validValuesIsNull).to.be.a('boolean');
              expect(data.validValuesIsNull).to.be(false);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getExtensions', function() {
        it('should call getExtensions successfully', function(done) {
          // TODO: uncomment getExtensions call and complete the assertions
          /*

          instance.getExtensions(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(PowerBiReportServerRestApi.Extension);
              expect(data.extensionType).to.be.a(PowerBiReportServerRestApi.ExtensionType);
                  expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.localizedName).to.be.a('string');
              expect(data.localizedName).to.be("");
              expect(data.visible).to.be.a('boolean');
              expect(data.visible).to.be(false);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('validateExtensionParameters', function() {
        it('should call validateExtensionParameters successfully', function(done) {
          // TODO: uncomment, update parameter values for validateExtensionParameters call and complete the assertions
          /*
          var opts = {};
          opts.extensionSettings = new PowerBiReportServerRestApi.ExtensionSettings();
          opts.extensionSettings.extension = "";
          opts.extensionSettings.parameterValues = new PowerBiReportServerRestApi.ParameterValue();
          opts.extensionSettings.parameterValues.name = "";
          opts.extensionSettings.parameterValues.value = "";
          opts.extensionSettings.parameterValues.isValueFieldReference = false;

          instance.validateExtensionParameters(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(PowerBiReportServerRestApi.ExtensionParameter);
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.displayName).to.be.a('string');
              expect(data.displayName).to.be("");
              expect(data.required).to.be.a('boolean');
              expect(data.required).to.be(false);
              expect(data.readOnly).to.be.a('boolean');
              expect(data.readOnly).to.be(false);
              expect(data.value).to.be.a('string');
              expect(data.value).to.be("");
              expect(data.error).to.be.a('string');
              expect(data.error).to.be("");
              expect(data.encrypted).to.be.a('boolean');
              expect(data.encrypted).to.be(false);
              expect(data.isPassword).to.be.a('boolean');
              expect(data.isPassword).to.be(false);
              {
                let dataCtr = data.validValues;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(PowerBiReportServerRestApi.ValidValue);
                  expect(data.label).to.be.a('string');
                  expect(data.label).to.be("");
                  expect(data.value).to.be.a('string');
                  expect(data.value).to.be("");
                }
              }
              expect(data.validValuesIsNull).to.be.a('boolean');
              expect(data.validValuesIsNull).to.be(false);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
