/*
 * Power BI Report Server REST API
 * The Power BI Report Server REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Since Power BI Report Server is a superset of SQL Server Reporting Services, the Power BI Report Server REST API is a superset of the  [SQL Server Reporting Services REST API](https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0).  __Power BI Report Server API Additions__ * January 2019 Release   * /PowerBIReports({Id})/DataModelRoles (GET)   * /PowerBIReports({Id})/DataModelRoleAssignments (GET & PUT)  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://powerbi.microsoft.com/documentation/reportserver-developer-handbook-overview/  __Team Blog:__  https://powerbi.microsoft.com/blog/  __Support forums:__  https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer 
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PowerBiReportServerRestApi);
  }
}(this, function(expect, PowerBiReportServerRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PowerBiReportServerRestApi.SystemApi();
  });

  describe('(package)', function() {
    describe('SystemApi', function() {
      describe('getSystemAllowedActions', function() {
        it('should call getSystemAllowedActions successfully', function(done) {
          // TODO: uncomment getSystemAllowedActions call and complete the assertions
          /*

          instance.getSystemAllowedActions(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PowerBiReportServerRestApi.ODataAllowedActions);
            expect(data.odataContext).to.be.a('string');
            expect(data.odataContext).to.be("");
            {
              let dataCtr = data.value;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PowerBiReportServerRestApi.AllowedAction);
                expect(data.action).to.be.a('string');
                expect(data.action).to.be("");
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSystemInfo', function() {
        it('should call getSystemInfo successfully', function(done) {
          // TODO: uncomment getSystemInfo call and complete the assertions
          /*

          instance.getSystemInfo(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PowerBiReportServerRestApi.SystemInfo);
            expect(data.reportServerAbsoluteUrl).to.be.a('string');
            expect(data.reportServerAbsoluteUrl).to.be("");
            expect(data.reportServerRelativeUrl).to.be.a('string');
            expect(data.reportServerRelativeUrl).to.be("");
            expect(data.webPortalRelativeUrl).to.be.a('string');
            expect(data.webPortalRelativeUrl).to.be("");
            expect(data.productName).to.be.a('string');
            expect(data.productName).to.be("");
            expect(data.productVersion).to.be.a('string');
            expect(data.productVersion).to.be("");
            expect(data.productType).to.be.a('string');
            expect(data.productType).to.be("PowerBiReportServer");
            expect(data.timeZone).to.be.a('string');
            expect(data.timeZone).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSystemPolicies', function() {
        it('should call getSystemPolicies successfully', function(done) {
          // TODO: uncomment getSystemPolicies call and complete the assertions
          /*

          instance.getSystemPolicies(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(PowerBiReportServerRestApi.Policy);
              expect(data.groupUserName).to.be.a('string');
              expect(data.groupUserName).to.be("");
              {
                let dataCtr = data.roles;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(PowerBiReportServerRestApi.Role);
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("");
                  expect(data.description).to.be.a('string');
                  expect(data.description).to.be("");
                }
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSystemProperties', function() {
        it('should call getSystemProperties successfully', function(done) {
          // TODO: uncomment, update parameter values for getSystemProperties call and complete the assertions
          /*
          var opts = {};
          opts.properties = ["properties_example"];

          instance.getSystemProperties(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PowerBiReportServerRestApi.ODataProperties);
            expect(data.odataContext).to.be.a('string');
            expect(data.odataContext).to.be("");
            {
              let dataCtr = data.value;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(PowerBiReportServerRestApi.Property);
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.value).to.be.a('string');
                expect(data.value).to.be("");
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setSystemPolicies', function() {
        it('should call setSystemPolicies successfully', function(done) {
          // TODO: uncomment, update parameter values for setSystemPolicies call
          /*
          var systemPolicy = new PowerBiReportServerRestApi.SystemPolicy();
          systemPolicy.id = """00000000-0000-0000-0000-000000000000";
          systemPolicy.policies = [new PowerBiReportServerRestApi.Policy()];
          systemPolicy.policies[0].groupUserName = "";
          systemPolicy.policies[0].roles = [new PowerBiReportServerRestApi.Role()];
          systemPolicy.policies[0].roles[0].name = "";
          systemPolicy.policies[0].roles[0].description = "";

          instance.setSystemPolicies(systemPolicy, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateSystemProperties', function() {
        it('should call updateSystemProperties successfully', function(done) {
          // TODO: uncomment, update parameter values for updateSystemProperties call
          /*
          var properties = [new PowerBiReportServerRestApi.Property()];
          properties[0].name = "";
          properties[0].value = "";

          instance.updateSystemProperties(properties, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
