require.config({
    baseUrl: "./scripts/",
    paths: {
        'jquery': "/powerbi/libs/scripts/jquery",
        'angular': "libs/angular/angular",
        'angular-route': 'libs/angular-route/angular-route',
        'ui.route': 'libs/angular-plugins/angular-ui-router/angular-ui-router.min',
        'angularAMD': 'libs/angular-plugins/angularAMD',
        'blockUI': 'libs/angular-plugins/angular-block-ui/angular-block-ui',
        'ngload': 'libs/angular-plugins/ngload',
        'ui-bootstrap': 'libs/angular-plugins/angular-ui-bootstrap/ui-bootstrap-tpls-0.12.1.min',
        'angular-sanitize': 'libs/angular-plugins/angular-sanitize.min',
        'css': 'libs/requirejs/css.min',
        'ueditorConfig': 'libs/ueditor/ueditor.config',
        'ueditorAll': 'libs/ueditor/ueditor.all.min',
        'wdatePicker': 'libs/My97DatePicker/WdatePicker',
        'pbirs': "index",
        "ApiClient": "ApiClient",
        "CacheRefreshPlansApi": "api/CacheRefreshPlansApi",
        "CatalogItemsApi": "api/CatalogItemsApi",
        "DataSetsApi": "api/DataSetsApi",
        "DataSourcesApi": "api/DataSourcesApi",
        "ExcelWorkbooksApi": "api/ExcelWorkbooksApi",
        "ExtensionsApi": "api/ExtensionsApi",
        "FavoriteItemsApi": "api/FavoriteItemsApi",
        "FoldersApi": "api/FoldersApi",
        "KpisApi": "api/KpisApi",
        "LinkedReportsApi": "api/LinkedReportsApi",
        "MeApi": "api/MeApi",
        "MobileReportsApi": "api/MobileReportsApi",
        "PowerBIReportsApi": "api/PowerBIReportsApi",
        "ReportsApi": "api/ReportsApi",
        "ResourcesApi": "api/ResourcesApi",
        "SessionApi": "api/SessionApi",
        "SubscriptionsApi": "api/SubscriptionsApi",
        "SystemApi": "api/SystemApi",
        "AllowedAction":"model/AllowedAction",
        "BulkOperationsResult":"model/BulkOperationsResult",
        "CacheOptions":"model/CacheOptions",
        "CacheRefreshPlan":"model/CacheRefreshPlan",
        "CatalogItem":"model/CatalogItem",
        "CatalogItemType":"model/CatalogItemType",
        "Comment":"model/Comment",
        "CredentialsStoredInServer":"model/CredentialsStoredInServer",
        "CredentialsSuppliedByUser":"model/CredentialsSuppliedByUser",
        "DailyRecurrence":"model/DailyRecurrence",
        "DataModelDataSource":"model/DataModelDataSource",
        "DataModelDataSourceAuthType":"model/DataModelDataSourceAuthType",
        "DataModelDataSourceKind":"model/DataModelDataSourceKind",
        "DataModelDataSourceType":"model/DataModelDataSourceType",
        "DataModelRole":"model/DataModelRole",
        "DataModelRoleAssignment":"model/DataModelRoleAssignment",
        "DataSet":"model/DataSet",
        "DataSetAggregateValueParameters":"model/DataSetAggregateValueParameters",
        "DataSetColumns":"model/DataSetColumns",
        "DataSetData":"model/DataSetData",
        "DataSetDataParameters":"model/DataSetDataParameters",
        "DataSetField":"model/DataSetField",
        "DataSetItem":"model/DataSetItem",
        "DataSetParameter":"model/DataSetParameter",
        "DataSetParameterInfo":"model/DataSetParameterInfo",
        "DataSetRow":"model/DataSetRow",
        "DataSetSchema":"model/DataSetSchema",
        "DataSource":"model/DataSource",
        "DataSourceCheckResult":"model/DataSourceCheckResult",
        "DaysOfWeekSelector":"model/DaysOfWeekSelector",
        "DeleteItemsRequest":"model/DeleteItemsRequest",
        "DrillthroughTarget":"model/DrillthroughTarget",
        "DrillthroughTargetType":"model/DrillthroughTargetType",
        "ExcelWorkbook":"model/ExcelWorkbook",
        "ExpirationReference":"model/ExpirationReference",
        "Extension":"model/Extension",
        "ExtensionParameter":"model/ExtensionParameter",
        "ExtensionSettings":"model/ExtensionSettings",
        "ExtensionType":"model/ExtensionType",
        "FavoriteItem":"model/FavoriteItem",
        "Folder":"model/Folder",
        "HistorySnapshot":"model/HistorySnapshot",
        "HistorySnapshotOptions":"model/HistorySnapshotOptions",
        "ItemExecutionType":"model/ItemExecutionType",
        "ItemPolicy":"model/ItemPolicy",
        "Kpi":"model/Kpi",
        "KpiData":"model/KpiData",
        "KpiDataItem":"model/KpiDataItem",
        "KpiDataItemType":"model/KpiDataItemType",
        "KpiSharedDataItemAggregation":"model/KpiSharedDataItemAggregation",
        "KpiValueFormat":"model/KpiValueFormat",
        "KpiValues":"model/KpiValues",
        "KpiVisualization":"model/KpiVisualization",
        "LinkedReport":"model/LinkedReport",
        "ManifestItem":"model/ManifestItem",
        "MinuteRecurrence":"model/MinuteRecurrence",
        "MobileReport":"model/MobileReport",
        "MobileReportManifest":"model/MobileReportManifest",
        "MobileReportResourceGroupType":"model/MobileReportResourceGroupType",
        "MobileReportThumbnailType":"model/MobileReportThumbnailType",
        "MonthlyDOWRecurrence":"model/MonthlyDOWRecurrence",
        "MonthlyRecurrence":"model/MonthlyRecurrence",
        "MonthsOfYearSelector":"model/MonthsOfYearSelector",
        "MoveItemsRequest":"model/MoveItemsRequest",
        "ODataAllowedActions":"model/ODataAllowedActions",
        "ODataCacheRefreshPlans":"model/ODataCacheRefreshPlans",
        "ODataCatalogItems":"model/ODataCatalogItems",
        "ODataComments":"model/ODataComments",
        "ODataDataModelRoleAssignments":"model/ODataDataModelRoleAssignments",
        "ODataDataModelRoles":"model/ODataDataModelRoles",
        "ODataDataSetRows":"model/ODataDataSetRows",
        "ODataDataSets":"model/ODataDataSets",
        "ODataDataSources":"model/ODataDataSources",
        "ODataDependentItems":"model/ODataDependentItems",
        "OdataError":"model/OdataError",
        "OdataErrorDetail":"model/OdataErrorDetail",
        "OdataErrorMain":"model/OdataErrorMain",
        "ODataExcelWorkbooks":"model/ODataExcelWorkbooks",
        "ODataFolders":"model/ODataFolders",
        "ODataKpis":"model/ODataKpis",
        "ODataLinkedReports":"model/ODataLinkedReports",
        "ODataMobileReport":"model/ODataMobileReport",
        "ODataPowerBIReports":"model/ODataPowerBIReports",
        "ODataProperties":"model/ODataProperties",
        "ODataProperties1":"model/ODataProperties1",
        "ODataQueryFields":"model/ODataQueryFields",
        "ODataReportParameterDefinitions":"model/ODataReportParameterDefinitions",
        "ODataReports":"model/ODataReports",
        "ODataResources":"model/ODataResources",
        "ODataSubscriptionHistory":"model/ODataSubscriptionHistory",
        "ParameterValue":"model/ParameterValue",
        "Policy":"model/Policy",
        "PowerBIReport":"model/PowerBIReport",
        "Property":"model/Property",
        "Query":"model/Query",
        "QueryFieldsRequest":"model/QueryFieldsRequest",
        "Report":"model/Report",
        "ReportHistorySnapshotsOptions":"model/ReportHistorySnapshotsOptions",
        "ReportParameterDefinition":"model/ReportParameterDefinition",
        "ReportParameterDefinitionPatch":"model/ReportParameterDefinitionPatch",
        "ReportParameterState":"model/ReportParameterState",
        "ReportParameterType":"model/ReportParameterType",
        "ReportParameterVisibility":"model/ReportParameterVisibility",
        "Resource":"model/Resource",
        "ResourceGroup":"model/ResourceGroup",
        "ResourceItem":"model/ResourceItem",
        "Role":"model/Role",
        "ScheduleDefinition":"model/ScheduleDefinition",
        "ScheduleRecurrence":"model/ScheduleRecurrence",
        "ScheduleReference":"model/ScheduleReference",
        "SharedDataSetPath":"model/SharedDataSetPath",
        "SharedDataSets":"model/SharedDataSets",
        "Subscription":"model/Subscription",
        "SubscriptionHistory":"model/SubscriptionHistory",
        "SystemInfo":"model/SystemInfo",
        "SystemPolicy":"model/SystemPolicy",
        "ThumbnailItem":"model/ThumbnailItem",
        "UpdateCacheSnapshotResult":"model/UpdateCacheSnapshotResult",
        "User":"model/User",
        "UserCredentials":"model/UserCredentials",
        "ValidValue":"model/ValidValue",
        "WeeklyRecurrence":"model/WeeklyRecurrence",
        "WeekNumberEnum":"model/WeekNumberEnum"
    },
    shim: {
        angular: {
            exports: 'angular',
            deps: ['jquery']
        },	// 表明该模块依赖angular
        'angularAMD': ['angular'],
        'angular-route': ['angular'],
        'ui.route': ['angular'],
        'ueditorConfig': ['jquery'],
        'ueditorAll': ['jquery'],
        'wdatePicker': ['jquery'],
        'ui-bootstrap': ['angular'],
        'blockUI': ['angular'],
        'angular-sanitize': ['angular']
    },
    urlArgs : "v=" + new Date().getTime(),
    // 启动程序 scripts/app.js
    deps : [ 'app' ]
});