/*
 * SQL Server 2017 Reporting Services REST API
 * The SQL Server 2017 Reporting Services REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://docs.microsoft.com/sql/reporting-services/reporting-services-developer-documentation  __Team Blog:__ https://blogs.msdn.microsoft.com/sqlrsteamblog  __Support forums:__ https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlreportingservices 
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CatalogItem', 'model/CatalogItemType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CatalogItem'), require('./CatalogItemType'));
  } else {
    // Browser globals (root is window)
    if (!root.SqlServer2017ReportingServicesRestApi) {
      root.SqlServer2017ReportingServicesRestApi = {};
    }
    root.SqlServer2017ReportingServicesRestApi.LinkedReport = factory(root.SqlServer2017ReportingServicesRestApi.ApiClient, root.SqlServer2017ReportingServicesRestApi.CatalogItem, root.SqlServer2017ReportingServicesRestApi.CatalogItemType);
  }
}(this, function(ApiClient, CatalogItem, CatalogItemType) {
  'use strict';

  /**
   * The LinkedReport model module.
   * @module model/LinkedReport
   * @version 2.0
   */

  /**
   * Constructs a new <code>LinkedReport</code>.
   * @alias module:model/LinkedReport
   * @class
   * @extends module:model/CatalogItem
   */
  var exports = function() {
    CatalogItem.call(this);
  };

  /**
   * Constructs a <code>LinkedReport</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LinkedReport} obj Optional instance to populate.
   * @return {module:model/LinkedReport} The populated <code>LinkedReport</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      CatalogItem.constructFromObject(data, obj);
      if (data.hasOwnProperty('HasParameters'))
        obj.hasParameters = ApiClient.convertToType(data['HasParameters'], 'Boolean');
      if (data.hasOwnProperty('Link'))
        obj.link = ApiClient.convertToType(data['Link'], 'String');
    }
    return obj;
  }

  exports.prototype = Object.create(CatalogItem.prototype);
  exports.prototype.constructor = exports;
  /**
   * A boolean value that indicates whether the LinkedReport has parameters.
   * @member {Boolean} hasParameters
   */
  exports.prototype.hasParameters = undefined;

  /**
   *  A string value that specifies the path to the report item that this linked report is linked to.
   * @member {String} link
   */
  exports.prototype.link = undefined;

  return exports;

}));
