/*
 * SQL Server 2017 Reporting Services REST API
 * The SQL Server 2017 Reporting Services REST API provides programmatic access to the report server catalog.  For example, basic CRUD operations can be done on folders, reports, KPIs, data sources, datasets, refresh plans, subscriptions, etc.     The REST API can also be used to provide more advanced functionality, such as: * Navigate the folder hierarchy * Discover the contents of a folder * Download a report definition * Modify default report parameters * Change or execute a refresh plan * A whole lot more  The REST API is a RESTful successor to the legacy [SOAP API](https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.aspx).  Happy coding!  __API samples:__ https://github.com/Microsoft/Reporting-Services  __Developer documentation:__ https://docs.microsoft.com/sql/reporting-services/reporting-services-developer-documentation  __Team Blog:__ https://blogs.msdn.microsoft.com/sqlrsteamblog  __Support forums:__ https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlreportingservices 
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DataSetItem', 'model/ResourceGroup', 'model/ThumbnailItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DataSetItem'), require('./ResourceGroup'), require('./ThumbnailItem'));
  } else {
    // Browser globals (root is window)
    if (!root.SqlServer2017ReportingServicesRestApi) {
      root.SqlServer2017ReportingServicesRestApi = {};
    }
    root.SqlServer2017ReportingServicesRestApi.MobileReportManifest = factory(root.SqlServer2017ReportingServicesRestApi.ApiClient, root.SqlServer2017ReportingServicesRestApi.DataSetItem, root.SqlServer2017ReportingServicesRestApi.ResourceGroup, root.SqlServer2017ReportingServicesRestApi.ThumbnailItem);
  }
}(this, function(ApiClient, DataSetItem, ResourceGroup, ThumbnailItem) {
  'use strict';

  /**
   * The MobileReportManifest model module.
   * @module model/MobileReportManifest
   * @version 2.0
   */

  /**
   * Constructs a new <code>MobileReportManifest</code>.
   * An object that contains the specification of the contents of a mobile report.
   * @alias module:model/MobileReportManifest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>MobileReportManifest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MobileReportManifest} obj Optional instance to populate.
   * @return {module:model/MobileReportManifest} The populated <code>MobileReportManifest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Resources'))
        obj.resources = ApiClient.convertToType(data['Resources'], [ResourceGroup]);
      if (data.hasOwnProperty('DataSets'))
        obj.dataSets = ApiClient.convertToType(data['DataSets'], [DataSetItem]);
      if (data.hasOwnProperty('Thumbnails'))
        obj.thumbnails = ApiClient.convertToType(data['Thumbnails'], [ThumbnailItem]);
    }
    return obj;
  }

  /**
   * An array of items of type ResourceGroup that specify the resources referenced in this MobileReport. A Resource is a generalized object and its content type is undefined.  A client must be able to understand the content returned in the Resource.
   * @member {Array.<module:model/ResourceGroup>} resources
   */
  exports.prototype.resources = undefined;

  /**
   * An array of objects of type DataSetItem that specifies the DataSets referenced in this MobileReport.
   * @member {Array.<module:model/DataSetItem>} dataSets
   */
  exports.prototype.dataSets = undefined;

  /**
   * An array of items of type ThumbnailItem that contains the Thumbnails associated with the MobileReport.
   * @member {Array.<module:model/ThumbnailItem>} thumbnails
   */
  exports.prototype.thumbnails = undefined;

  return exports;

}));
